[book]
title = "złotówa"
authors = ["Kamil Jeziorny"]
language = "en"
src = "src"

[output.html]
default-theme = "coal"
preferred-dark-theme = "coal"
git-repository-url = "https://github.com/kamiljeziorny/zlotowa"
